### ISSUE TITLE
Calculate the white noise associated with the (on-off) value by subtracting adjacent frequencies

### ISSUE THREAD

**Issue by kfornaz** [meerklass/museek#105]
@mariogrs  mentioned that : The on-off measurement is supposed to give: g(t,nu)*[Tb+Tdiode] - g(t,nu)*[Tb] = g(t,nu)*Tdiode. Where Tb is the background. If Tdiode is constant in time, this will be proportional to the 1f noise in g(t,nu).

[https://meerklass.slack.com/archives/C07LXGG693R/p1726476411158569](url)

**Comment by wkhu-astro** [comment]
The white noise is also estimated using ABBA method.

**Comment by wkhu-astro** [comment]
The white noise is estimated by subtracting adjacent frequencies, this is finished.   The white noise is also estimated using ABBA method now, the results from ABBA is good.  Now we use ABBA.
