### ISSUE TITLE
Saving visibilities

### ISSUE THREAD

**Issue by mariogrs** [meerklass/museek#65]
https://github.com/meerklass/museek/blob/ddb371a25248ed1741ed1c09567448bc120cfacc/museek/config/sanity_check.py#L19C9-L19C9

Shouldn't this be FALSE by default since we already have the split single dish data on disk?

**Comment by amadeuswi** [comment]
Yes we have split single dish data, but it's still in a worst possible type of dask arrays for our purpose. They take forever to load. Therefore we save the visibilities to disk by default - in `numpy` format

**Comment by mariogrs** [comment]
OK
