### ISSUE TITLE
Sanity check - dish elevation

### ISSUE THREAD

**Issue by mariogrs** [meerklass/museek#85]
Confirm if the elevation check for the dishes (if they keep the correct elevation) takes into account what we call stragglers - dishes that have been identified by the office as not moving correctly. I think this might affect the calculation if it's not correct.

**Comment by piyanatk** [comment]
@mariogrs I am still trying to understand the problem. The stragglers are dishes that got stuck during slew, so they ended up missing some scans, correct? Are these incidents not accounted for in all the elevation plots?

**Comment by mariogrs** [comment]
Actually, I think it's better for Wenkai to look at this since he wrote the elevation checks. Let me assign to him.

**Comment by wkhu-astro** [comment]
The elevation check in the sanity check will be performed for each antenna individually, including those that are stragglers.

**Comment by mariogrs** [comment]
Then I think this is fine. We can close the issue.
